### ISSUE TITLE
Services API not working.

### ISSUE THREAD

**Issue by priyamkanojia** [thapatechnical/reactmultipage#1]
https://thapareactapi.up.railway.app this API link is not working.

**Comment by thapatechnical** [comment]
Hi, 
Sorry for that. But the actual reason is Railway is now started charging and we don't have paid subscriptions. 
Hope you understand.

**Comment by thapatechnical** [comment]
Hii,
I commented on your issue on GitHub Page ok.

Thanks

**Comment by priyamkanojia** [comment]
Ok, Thanks.
